import {
  Smartphone,
  Laptop,
  Monitor,
  Tv,
  Headphones,
  Camera,
  Watch,
  Gamepad2,
  Printer,
  Router,
  HardDrive,
  Cpu,
  MemoryStick,
  Mouse,
  Keyboard,
  Speaker,
  Mic,
  Battery,
  Usb,
  Wifi,
  Bluetooth,
  Tablet,
  Home,
  Refrigerator,
  WashingMachine,
  Fan,
  Lightbulb,
  Plug,
  Thermometer,
  Wind,
  Droplets,
  Flame,
  Zap,
  Shield,
  Lock,
  Key,
  Eye,
  Bell,
  Video,
  Cctv,
  Scan,
  Fingerprint,
  Car,
  Bike,
  Plane,
  Train,
  Truck,
  Wrench,
  Settings,
  Hammer,
  Scissors,
  Paintbrush,
  PaintBucket,
  Ruler,
  Package,
  ShoppingBag,
  ShoppingCart,
  Gift,
  Tag,
  Percent,
  CreditCard,
  Wallet,
  DollarSign,
  Briefcase,
  Building,
  Store,
  Warehouse,
  Factory,
  Users,
  User,
  Baby,
  Heart,
  Activity,
  Pill,
  Stethoscope,
  Dumbbell,
  Trophy,
  Medal,
  Target,
  Flag,
  Map,
  Compass,
  Globe,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Shirt,
  Footprints,
  Glasses,
  GraduationCap,
  BookOpen,
  Notebook,
  PenTool,
  Palette,
  Music,
  Film,
  Image,
  Folder,
  FileText,
  Mail,
  Phone,
  MessageSquare,
  Share2,
  Link,
  Download,
  Upload,
  Server,
  Database,
  Cloud as CloudIcon,
  Code,
  Terminal,
  Box,
  Boxes,
  Grid,
  Layers,
  Layout,
  Aperture,
  Focus,
  Maximize,
  Minimize,
  Move,
  RotateCw,
  RefreshCw,
  Repeat,
  Play,
  Pause,
  Power,
  ToggleLeft,
  ToggleRight,
  Volume2,
  VolumeX,
  Radio,
  Podcast,
  Rss,
  Satellite,
  Signal,
  Antenna,
  Cable,
  CircuitBoard,
  LucideIcon,
} from 'lucide-react';

export interface CategoryIconOption {
  name: string;
  icon: LucideIcon;
  category: string;
}

export const categoryIcons: CategoryIconOption[] = [
  { name: 'smartphone', icon: Smartphone, category: 'Electronics' },
  { name: 'laptop', icon: Laptop, category: 'Electronics' },
  { name: 'monitor', icon: Monitor, category: 'Electronics' },
  { name: 'tv', icon: Tv, category: 'Electronics' },
  { name: 'headphones', icon: Headphones, category: 'Electronics' },
  { name: 'camera', icon: Camera, category: 'Electronics' },
  { name: 'watch', icon: Watch, category: 'Electronics' },
  { name: 'gamepad2', icon: Gamepad2, category: 'Electronics' },
  { name: 'printer', icon: Printer, category: 'Electronics' },
  { name: 'router', icon: Router, category: 'Electronics' },
  { name: 'hard-drive', icon: HardDrive, category: 'Electronics' },
  { name: 'cpu', icon: Cpu, category: 'Electronics' },
  { name: 'memory-stick', icon: MemoryStick, category: 'Electronics' },
  { name: 'mouse', icon: Mouse, category: 'Electronics' },
  { name: 'keyboard', icon: Keyboard, category: 'Electronics' },
  { name: 'speaker', icon: Speaker, category: 'Electronics' },
  { name: 'mic', icon: Mic, category: 'Electronics' },
  { name: 'battery', icon: Battery, category: 'Electronics' },
  { name: 'usb', icon: Usb, category: 'Electronics' },
  { name: 'wifi', icon: Wifi, category: 'Electronics' },
  { name: 'bluetooth', icon: Bluetooth, category: 'Electronics' },
  { name: 'tablet', icon: Tablet, category: 'Electronics' },
  { name: 'radio', icon: Radio, category: 'Electronics' },
  { name: 'podcast', icon: Podcast, category: 'Electronics' },
  { name: 'satellite', icon: Satellite, category: 'Electronics' },
  { name: 'signal', icon: Signal, category: 'Electronics' },
  { name: 'antenna', icon: Antenna, category: 'Electronics' },
  { name: 'cable', icon: Cable, category: 'Electronics' },
  { name: 'circuit-board', icon: CircuitBoard, category: 'Electronics' },

  { name: 'home', icon: Home, category: 'Home' },
  { name: 'refrigerator', icon: Refrigerator, category: 'Home' },
  { name: 'washing-machine', icon: WashingMachine, category: 'Home' },
  { name: 'fan', icon: Fan, category: 'Home' },
  { name: 'lightbulb', icon: Lightbulb, category: 'Home' },
  { name: 'plug', icon: Plug, category: 'Home' },
  { name: 'thermometer', icon: Thermometer, category: 'Home' },
  { name: 'wind', icon: Wind, category: 'Home' },
  { name: 'droplets', icon: Droplets, category: 'Home' },
  { name: 'flame', icon: Flame, category: 'Home' },
  { name: 'zap', icon: Zap, category: 'Home' },
  { name: 'power', icon: Power, category: 'Home' },

  { name: 'shield', icon: Shield, category: 'Security' },
  { name: 'lock', icon: Lock, category: 'Security' },
  { name: 'key', icon: Key, category: 'Security' },
  { name: 'eye', icon: Eye, category: 'Security' },
  { name: 'bell', icon: Bell, category: 'Security' },
  { name: 'video', icon: Video, category: 'Security' },
  { name: 'cctv', icon: Cctv, category: 'Security' },
  { name: 'scan', icon: Scan, category: 'Security' },
  { name: 'fingerprint', icon: Fingerprint, category: 'Security' },

  { name: 'car', icon: Car, category: 'Transport' },
  { name: 'bike', icon: Bike, category: 'Transport' },
  { name: 'plane', icon: Plane, category: 'Transport' },
  { name: 'train', icon: Train, category: 'Transport' },
  { name: 'truck', icon: Truck, category: 'Transport' },

  { name: 'wrench', icon: Wrench, category: 'Tools' },
  { name: 'settings', icon: Settings, category: 'Tools' },
  { name: 'hammer', icon: Hammer, category: 'Tools' },
  { name: 'scissors', icon: Scissors, category: 'Tools' },
  { name: 'paintbrush', icon: Paintbrush, category: 'Tools' },
  { name: 'paint-bucket', icon: PaintBucket, category: 'Tools' },
  { name: 'ruler', icon: Ruler, category: 'Tools' },

  { name: 'package', icon: Package, category: 'Shopping' },
  { name: 'shopping-bag', icon: ShoppingBag, category: 'Shopping' },
  { name: 'shopping-cart', icon: ShoppingCart, category: 'Shopping' },
  { name: 'gift', icon: Gift, category: 'Shopping' },
  { name: 'tag', icon: Tag, category: 'Shopping' },
  { name: 'percent', icon: Percent, category: 'Shopping' },
  { name: 'credit-card', icon: CreditCard, category: 'Shopping' },
  { name: 'wallet', icon: Wallet, category: 'Shopping' },
  { name: 'dollar-sign', icon: DollarSign, category: 'Shopping' },

  { name: 'briefcase', icon: Briefcase, category: 'Business' },
  { name: 'building', icon: Building, category: 'Business' },
  { name: 'store', icon: Store, category: 'Business' },
  { name: 'warehouse', icon: Warehouse, category: 'Business' },
  { name: 'factory', icon: Factory, category: 'Business' },

  { name: 'users', icon: Users, category: 'People' },
  { name: 'user', icon: User, category: 'People' },
  { name: 'baby', icon: Baby, category: 'People' },

  { name: 'heart', icon: Heart, category: 'Health' },
  { name: 'activity', icon: Activity, category: 'Health' },
  { name: 'pill', icon: Pill, category: 'Health' },
  { name: 'stethoscope', icon: Stethoscope, category: 'Health' },
  { name: 'dumbbell', icon: Dumbbell, category: 'Health' },

  { name: 'trophy', icon: Trophy, category: 'Sports' },
  { name: 'medal', icon: Medal, category: 'Sports' },
  { name: 'target', icon: Target, category: 'Sports' },
  { name: 'flag', icon: Flag, category: 'Sports' },

  { name: 'map', icon: Map, category: 'Travel' },
  { name: 'compass', icon: Compass, category: 'Travel' },
  { name: 'globe', icon: Globe, category: 'Travel' },
  { name: 'sun', icon: Sun, category: 'Travel' },
  { name: 'moon', icon: Moon, category: 'Travel' },
  { name: 'cloud', icon: Cloud, category: 'Travel' },
  { name: 'umbrella', icon: Umbrella, category: 'Travel' },

  { name: 'shirt', icon: Shirt, category: 'Fashion' },
  { name: 'footprints', icon: Footprints, category: 'Fashion' },
  { name: 'glasses', icon: Glasses, category: 'Fashion' },

  { name: 'graduation-cap', icon: GraduationCap, category: 'Education' },
  { name: 'book-open', icon: BookOpen, category: 'Education' },
  { name: 'notebook', icon: Notebook, category: 'Education' },
  { name: 'pen-tool', icon: PenTool, category: 'Education' },

  { name: 'palette', icon: Palette, category: 'Media' },
  { name: 'music', icon: Music, category: 'Media' },
  { name: 'film', icon: Film, category: 'Media' },
  { name: 'image', icon: Image, category: 'Media' },
  { name: 'play', icon: Play, category: 'Media' },
  { name: 'volume2', icon: Volume2, category: 'Media' },

  { name: 'folder', icon: Folder, category: 'Office' },
  { name: 'file-text', icon: FileText, category: 'Office' },
  { name: 'mail', icon: Mail, category: 'Office' },
  { name: 'phone', icon: Phone, category: 'Office' },
  { name: 'message-square', icon: MessageSquare, category: 'Office' },

  { name: 'server', icon: Server, category: 'Tech' },
  { name: 'database', icon: Database, category: 'Tech' },
  { name: 'cloud-storage', icon: CloudIcon, category: 'Tech' },
  { name: 'code', icon: Code, category: 'Tech' },
  { name: 'terminal', icon: Terminal, category: 'Tech' },

  { name: 'box', icon: Box, category: 'Other' },
  { name: 'boxes', icon: Boxes, category: 'Other' },
  { name: 'grid', icon: Grid, category: 'Other' },
  { name: 'layers', icon: Layers, category: 'Other' },
  { name: 'layout', icon: Layout, category: 'Other' },
  { name: 'aperture', icon: Aperture, category: 'Other' },
  { name: 'focus', icon: Focus, category: 'Other' },
  { name: 'rss', icon: Rss, category: 'Other' },
];

export const iconCategories = [
  'Electronics',
  'Home',
  'Security',
  'Transport',
  'Tools',
  'Shopping',
  'Business',
  'People',
  'Health',
  'Sports',
  'Travel',
  'Fashion',
  'Education',
  'Media',
  'Office',
  'Tech',
  'Other',
];

export function getIconByName(name: string | null): LucideIcon | null {
  if (!name) return null;
  const iconOption = categoryIcons.find(opt => opt.name === name);
  return iconOption?.icon || null;
}

export function getIconsByCategory(category: string): CategoryIconOption[] {
  return categoryIcons.filter(opt => opt.category === category);
}

const keywordIconMap: Record<string, string> = {
  'computer': 'laptop',
  'kompyuter': 'laptop',
  'komputer': 'laptop',
  'pc': 'laptop',
  'desktop': 'monitor',
  'laptop': 'laptop',
  'noutbuk': 'laptop',
  'notebook': 'laptop',
  'ноутбук': 'laptop',
  'компьютер': 'laptop',

  'phone': 'smartphone',
  'smartphone': 'smartphone',
  'telefon': 'smartphone',
  'смартфон': 'smartphone',
  'телефон': 'smartphone',
  'mobile': 'smartphone',
  'mobil': 'smartphone',
  'iphone': 'smartphone',
  'android': 'smartphone',
  'samsung': 'smartphone',
  'xiaomi': 'smartphone',

  'tablet': 'tablet',
  'planshet': 'tablet',
  'планшет': 'tablet',
  'ipad': 'tablet',

  'tv': 'tv',
  'television': 'tv',
  'televizor': 'tv',
  'телевизор': 'tv',
  'smart tv': 'tv',
  'oled': 'tv',
  'led': 'tv',

  'headphone': 'headphones',
  'headphones': 'headphones',
  'naushnik': 'headphones',
  'наушники': 'headphones',
  'earphone': 'headphones',
  'earbuds': 'headphones',
  'airpods': 'headphones',
  'audio': 'headphones',

  'speaker': 'speaker',
  'kolonka': 'speaker',
  'колонка': 'speaker',
  'динамик': 'speaker',
  'sound': 'speaker',
  'bluetooth speaker': 'speaker',

  'camera': 'camera',
  'kamera': 'camera',
  'камера': 'camera',
  'photo': 'camera',
  'foto': 'camera',
  'фото': 'camera',
  'dslr': 'camera',
  'mirrorless': 'camera',

  'watch': 'watch',
  'soat': 'watch',
  'часы': 'watch',
  'smartwatch': 'watch',
  'smart watch': 'watch',
  'apple watch': 'watch',

  'game': 'gamepad2',
  'gaming': 'gamepad2',
  'oyun': 'gamepad2',
  'игр': 'gamepad2',
  'playstation': 'gamepad2',
  'xbox': 'gamepad2',
  'nintendo': 'gamepad2',
  'console': 'gamepad2',
  'joystick': 'gamepad2',

  'printer': 'printer',
  'printerlar': 'printer',
  'принтер': 'printer',
  'print': 'printer',
  'scanner': 'printer',
  'skaner': 'printer',

  'router': 'router',
  'modem': 'router',
  'wifi': 'wifi',
  'internet': 'router',

  'keyboard': 'keyboard',
  'klaviatura': 'keyboard',
  'клавиатура': 'keyboard',

  'mouse': 'mouse',
  'sichqoncha': 'mouse',
  'мышь': 'mouse',
  'мышка': 'mouse',

  'monitor': 'monitor',
  'ekran': 'monitor',
  'монитор': 'monitor',
  'display': 'monitor',
  'screen': 'monitor',

  'storage': 'hard-drive',
  'hard drive': 'hard-drive',
  'hdd': 'hard-drive',
  'ssd': 'hard-drive',
  'disk': 'hard-drive',
  'накопитель': 'hard-drive',
  'память': 'memory-stick',
  'memory': 'memory-stick',
  'ram': 'memory-stick',
  'flash': 'usb',
  'usb': 'usb',

  'cpu': 'cpu',
  'processor': 'cpu',
  'protsessor': 'cpu',
  'процессор': 'cpu',

  'microphone': 'mic',
  'mikrofon': 'mic',
  'микрофон': 'mic',
  'mic': 'mic',

  'battery': 'battery',
  'batareya': 'battery',
  'аккумулятор': 'battery',
  'powerbank': 'battery',
  'power bank': 'battery',
  'charger': 'battery',
  'zaryadka': 'battery',

  'refrigerator': 'refrigerator',
  'fridge': 'refrigerator',
  'muzlatkich': 'refrigerator',
  'холодильник': 'refrigerator',
  'xolodilnik': 'refrigerator',

  'washing': 'washing-machine',
  'washer': 'washing-machine',
  'kir yuvish': 'washing-machine',
  'стиральн': 'washing-machine',
  'laundry': 'washing-machine',

  'air condition': 'wind',
  'konditsioner': 'wind',
  'кондиционер': 'wind',
  'ac': 'wind',
  'climate': 'wind',
  'iqlim': 'wind',

  'fan': 'fan',
  'ventilyator': 'fan',
  'вентилятор': 'fan',

  'heater': 'flame',
  'isitkich': 'flame',
  'обогреватель': 'flame',
  'heating': 'flame',

  'light': 'lightbulb',
  'lamp': 'lightbulb',
  'chiroq': 'lightbulb',
  'лампа': 'lightbulb',
  'освещение': 'lightbulb',
  'led light': 'lightbulb',

  'vacuum': 'wind',
  'changyutkich': 'wind',
  'пылесос': 'wind',

  'microwave': 'zap',
  'mikrovolnovka': 'zap',
  'микроволн': 'zap',

  'oven': 'flame',
  'pech': 'flame',
  'печь': 'flame',
  'духовка': 'flame',

  'iron': 'thermometer',
  'dazmol': 'thermometer',
  'утюг': 'thermometer',

  'blender': 'zap',
  'mixer': 'zap',
  'миксер': 'zap',
  'блендер': 'zap',
  'kitchen': 'zap',
  'oshxona': 'zap',
  'кухн': 'zap',

  'security': 'shield',
  'xavfsizlik': 'shield',
  'безопасность': 'shield',
  'охран': 'shield',

  'cctv': 'cctv',
  'surveillance': 'cctv',
  'видеонаблюдение': 'cctv',
  'kuzatish': 'cctv',

  'alarm': 'bell',
  'signal': 'bell',
  'сигнализация': 'bell',

  'lock': 'lock',
  'qulf': 'lock',
  'замок': 'lock',
  'door': 'lock',
  'eshik': 'lock',
  'дверь': 'lock',

  'car': 'car',
  'avtomobil': 'car',
  'машина': 'car',
  'автомобиль': 'car',
  'auto': 'car',
  'avto': 'car',

  'bike': 'bike',
  'velosiped': 'bike',
  'велосипед': 'bike',
  'bicycle': 'bike',
  'moped': 'bike',
  'motorcycle': 'bike',
  'mototsikl': 'bike',
  'мотоцикл': 'bike',

  'tool': 'wrench',
  'asbob': 'wrench',
  'инструмент': 'wrench',
  'repair': 'wrench',
  'tamirlash': 'wrench',
  'ремонт': 'wrench',

  'sport': 'dumbbell',
  'fitness': 'dumbbell',
  'gym': 'dumbbell',
  'спорт': 'dumbbell',
  'exercise': 'dumbbell',

  'health': 'heart',
  'salomatlik': 'heart',
  'здоровье': 'heart',
  'medical': 'stethoscope',
  'tibbiy': 'stethoscope',
  'медицин': 'stethoscope',

  'beauty': 'heart',
  'go\'zallik': 'heart',
  'красота': 'heart',
  'cosmetic': 'heart',
  'kosmetika': 'heart',
  'косметик': 'heart',

  'fashion': 'shirt',
  'kiyim': 'shirt',
  'одежда': 'shirt',
  'clothes': 'shirt',
  'clothing': 'shirt',
  'apparel': 'shirt',

  'shoes': 'footprints',
  'poyabzal': 'footprints',
  'обувь': 'footprints',
  'footwear': 'footprints',

  'glasses': 'glasses',
  'ko\'zoynak': 'glasses',
  'очки': 'glasses',
  'eyewear': 'glasses',
  'sunglasses': 'glasses',

  'accessory': 'watch',
  'aksessuar': 'watch',
  'аксессуар': 'watch',
  'accessories': 'watch',

  'baby': 'baby',
  'bolalar': 'baby',
  'детск': 'baby',
  'child': 'baby',
  'kids': 'baby',
  'children': 'baby',

  'toy': 'gamepad2',
  'o\'yinchoq': 'gamepad2',
  'игрушк': 'gamepad2',
  'toys': 'gamepad2',

  'book': 'book-open',
  'kitob': 'book-open',
  'книг': 'book-open',
  'education': 'graduation-cap',
  'ta\'lim': 'graduation-cap',
  'образовани': 'graduation-cap',

  'office': 'briefcase',
  'ofis': 'briefcase',
  'офис': 'briefcase',

  'stationery': 'pen-tool',
  'kantselyariya': 'pen-tool',
  'канцеляр': 'pen-tool',

  'furniture': 'home',
  'mebel': 'home',
  'мебель': 'home',

  'garden': 'sun',
  'bog\'': 'sun',
  'сад': 'sun',
  'outdoor': 'sun',

  'pet': 'heart',
  'hayvon': 'heart',
  'животн': 'heart',
  'animal': 'heart',

  'gift': 'gift',
  'sovg\'a': 'gift',
  'подарок': 'gift',
  'present': 'gift',

  'sale': 'percent',
  'chegirma': 'percent',
  'скидк': 'percent',
  'discount': 'percent',
  'aksiya': 'percent',
  'акция': 'percent',

  'new': 'tag',
  'yangi': 'tag',
  'новинк': 'tag',
  'arrival': 'tag',

  'popular': 'trophy',
  'mashhur': 'trophy',
  'популярн': 'trophy',
  'trending': 'trophy',
  'bestseller': 'trophy',

  'cable': 'cable',
  'kabel': 'cable',
  'кабель': 'cable',
  'провод': 'cable',
  'wire': 'cable',
  'adapter': 'plug',
  'переходник': 'plug',

  'component': 'circuit-board',
  'komponent': 'circuit-board',
  'комплектующ': 'circuit-board',
  'part': 'circuit-board',
  'ehtiyot': 'circuit-board',
  'запчаст': 'circuit-board',

  'server': 'server',
  'network': 'server',
  'tarmoq': 'server',
  'сеть': 'server',
  'сервер': 'server',

  'software': 'code',
  'dastur': 'code',
  'программ': 'code',
  'app': 'code',
  'ilova': 'code',
  'приложени': 'code',

  'electronic': 'cpu',
  'elektronika': 'cpu',
  'электроник': 'cpu',

  'appliance': 'plug',
  'maishiy': 'plug',
  'бытов': 'plug',
  'техника': 'plug',
};

export function suggestIconForCategory(categoryName: string): string {
  const normalizedName = categoryName.toLowerCase().trim();

  for (const [keyword, iconName] of Object.entries(keywordIconMap)) {
    if (normalizedName.includes(keyword)) {
      return iconName;
    }
  }

  const words = normalizedName.split(/[\s\-_,]+/);
  for (const word of words) {
    if (word.length < 2) continue;
    for (const [keyword, iconName] of Object.entries(keywordIconMap)) {
      if (keyword.includes(word) || word.includes(keyword)) {
        return iconName;
      }
    }
  }

  return 'package';
}

export function getSemanticIcon(iconName: string | null, categoryName: string): LucideIcon {
  if (iconName) {
    const icon = getIconByName(iconName);
    if (icon) return icon;
  }

  const suggestedIconName = suggestIconForCategory(categoryName);
  const suggestedIcon = getIconByName(suggestedIconName);

  return suggestedIcon || Package;
}
